### ISSUE TITLE
Bug: Srednia ocena nie wyswietla sie przy przegladaniu kursow nauczyciela

### ISSUE THREAD

**Issue by MichLuszcz** [mGarbowski/pap-projekt#100]
W profilu nauczyciela wyswietlają się kursy, ale nawet jeśli kurs ma jakieś oceny to jego średnia nie wyświetla się żadna. 
Według mnie najlepiej jakby sie wyświetlała wiadomość N/D albo N/A albo "brak ocen" czy coś w sytuacji gdy ocen nie ma. A gdy są to wiadomo

**Comment by mbienkowsk** [comment]
dobra sysy sie zrobi
