### ISSUE TITLE
endpoint for editing an existing comment

### ISSUE THREAD

**Issue by mbienkowsk** [mGarbowski/pap-projekt#126]
editing reviews as of now just deletes the existing review and posts a new one. while this is not perfect (timestamp of posting changes, so the order of the reviews is mixed up), it can work for reviews as it also makes some sense to do it this way and treat an edited review as a new one. With comments, this cannot be done in this manner since if there's a discussion going on, we can't make editing a comment move it to the bottom. we would need to just update the text in an existing object in the db, so we need an endpoint for doing it, sth like /comments/commendId/edit? Also, if it's gonna be done the proper way for comments, might also do it for reviews

**Comment by MichLuszcz** [comment]
dodałem oddzielne issue na edytowanie reviews
