### ISSUE TITLE
App shuts down when normal user asks for a user

### ISSUE THREAD

**Issue by MichLuszcz** [mGarbowski/pap-projekt#153]
When logged in as a normal user, sending a GET on /api/users/{username} will throw an AccessDeniedException: Access Denied, which is not handled anywhere and breaks the app.

Tested on:
logged in as rdeckard
sent GET /api/users/rdeckard
Could not Get response

in backend:
Caused by: org.springframework.security.access.AccessDeniedException: Access Denied

**Comment by mGarbowski** [comment]
naprawione przez #154
