### ISSUE TITLE
Ustawienie CI/CD do pracy z bazą danych i serwowanie aplikacji webowej

### ISSUE THREAD

**Issue by mGarbowski** [mGarbowski/pap-projekt#25]
* [x] założyć konta dla chłopaków 
* [x] każdy wkleja klucz publiczny tutaj
* [x] zabezpieczenie merge requestów
* [x] napisać instrukcję pracy z serwerem
* [x] konfiguracja aplikacji frontendowej z dockerem
    * [x] odpowiedni Dockerfile, do przetestowania lokalnie
    * [x] GitHub Action budujące obraz i uploadujące na Docker Hub
* [x] skonfigurować reverse proxy Nginxa
* [x] postawić Postgresa na serwerze
* [x] dostosować i naprawić github actions
* [x] reusable workflows
    * [x] oddzielne dla budowania i publikowania, wdrażania 
    * [x] zbiorcze robiące wszystko (pełne wdrożenie)
* [x] oddzielne workflows uruchamiające testy
    * [x] backend
    * [x] frontend 
* [x] optymalizacja czasu budowania obrazu aplikacji frontendowej

**Comment by mbienkowsk** [comment]
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEA/g4mk+Tf9HBJtRq5IPX3bUpepADGaG6xi5ph7wjZn bienkowski.maksym@gmail.com

**Comment by Sawertynn** [comment]
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGA5r00GDkEprGA8LH9lIuwWf94Mw7CZ0v/5abI4y0+P sawertynn@gmx.com

**Comment by MichLuszcz** [comment]
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMtojQrO0RB+cRWks/uWUYFht+sfU7XWO8ytiQbxMSP+ michluszcz@gmail.com

**Comment by mGarbowski** [comment]
Macie założone konta
* mluszczek
* mbienkowski
* tkurzela

Instrukcja jest w [docsach](https://github.com/mGarbowski/pap-projekt/blob/main/docs/server.md)

Niech każdy z was spróbuje 
* sie zalogować (port 2222 !)
* czy może edytować/usuwać pliki w katalogu domowym
* tak samo w katalogu /srv/pap
* czy może korzystać z dockera `docker ps` `docker image ls`

i zostawcie reakcję pod komentarzem jeśli wszystko działa

**Comment by mGarbowski** [comment]
Aplikacja będzie dostępna pod domeną `pap.mgarbowski.pl`, działa już HTTPS :D

**Comment by mGarbowski** [comment]
Budowanie obrazu frontend trwa strasznie długo, może lepiej byłoby nie używać multi-stage build, tylko zbudować aplikację jako oddzielny krok i tylko skopiować rezultat podczas budowania obrazu (tak jak w docker-build-publish-backend)

**Comment by mGarbowski** [comment]
https://docs.github.com/en/actions/using-workflows/reusing-workflows

**Comment by mGarbowski** [comment]
Do przemyślenia użycie githubowego rejestru kontenerów, może da się ustawić jakjo prywatne(?)

**Comment by mGarbowski** [comment]
Gotowe
