### ISSUE TITLE
Endpointy do pobierania / dodawania opinii i komentarzy

### ISSUE THREAD

**Issue by mGarbowski** [mGarbowski/pap-projekt#33]
* [ ] ReviewController i CommentController
  * [x] sensowne endpointy rest np `/api/courses/{courseId}/reviews/{userId}` `/api/courses/{courseId}/reviews/{reviewerId}/comments/{commentatorId}`
  * [x] dobre linki tak jak przy domyślnie generowanych endpointach (do samego siebie i do powiązanych zasobów)
  * [ ] testy jednostkowe
  * [ ] testy integracyjne
  
  Napisałem "sensowne" bo to co się generuje automatycznie wygląda tak
![image](https://github.com/mGarbowski/pap-projekt/assets/53001098/042956b6-e33d-4da0-91cc-7a9ad7b8d89b)
i co gorsza nie działa

## Wymagania do Reviews
* Pobierz opinie dla kursu
* Pobierz opinie dla nauczyciela
* Pobierz wszystkie opinie wystawione przez użytkownika
* Dodaj opinię do kursu
  * użytkownik musi być zalogowany
  * może dodać opinię tylko jako on sam
* Edytuj opinię pod kursem
  * użytkownik możeedytować tylko swoją
* Usuń opinię
  * użytkownik może usunąc tlyko swoją
  * poprawne usunięcie (nawet jeśli takiej opinii już nie ma) zwraca 204
  * próba usunięcia kiedy nie mamy uprawnień powinna zwracać 403 

### Opinia musi zaweirać
* Username autora
* treść
* ocenę liczbową
* timestamp kiedy została dodana
* linki
  * self
  * komentarze pod tą opinią
  * link do autora komentarza

Czyli trzeba zwracać nie Review tylko ReviewDTO i tworzyć je customowymi zapytaniami do bazy

## Wymagania do komentarzy
* Pobierz komentarze pod opinią
* Pobierz komentarz (po id)
* Dodaj komentarz pod opinią
* Edytuj komentarz 
* Usuń komentarz

### Komentarz zawiera
* username autora
* tekst
* timestamp kiedy został dodany
* linki
  * self
  * autor komentarza
  
 To ma być w CommentDTO

**Comment by Sawertynn** [comment]
* [x] CommentController
  * [x] getCommentsForReview
  * [x] getCommendById
  * [x] getUserComments
  * [x] postComment (username, courseId)
  * [x] deleteComment

**Comment by mGarbowski** [comment]
@Sawertynn troche zaktualizowaliśmy wymagania odnośnie tych kontrolerów i co mają zwracać i kod Michała póki co jeszcze tego nie odzwierciedla więc jeśli masz jakiekolwiek wątpliwości co i jak testować to pytaj,

ja troche spierdoliłem z przemyśleniem tego i teraz trzeba zmieniać, sorry za to

jeśli już jakieś testy napisałeś to powinno się i tak w miare łatwo je zaadaptować tylko byle testowały dobre rzeczy
