### ISSUE TITLE
Add number of reviews to teacher and course DTOs so they can be displayed in the frontend

### ISSUE THREAD

**Issue by mbienkowsk** [mGarbowski/pap-projekt#94]

**Comment by mGarbowski** [comment]
* [x] dodać pole z liczbą opini do TeacherDTO i CourseDTO
* [x] zmienić zapytania w repozytoriach tak, żeby zwracały klasy encyjne a nie dto
* [x] w klasie service mapowanie z klasy encyjnej na klase dto
* [x] poprawić implememntacje serwisu, tak żeby wykonywać to mapowanie
* [x] sprawdzić czy implementacja kontrolera nie wymaga zmian
* [x] dopisać testy

przykłady jak są robione mapowania masz np w ReviewService
